# https://issues.apache.org/jira/browse/FINERACT-1453
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 13
    ignore:
      - dependency-name: "org.eclipse.persistence:eclipselink"
      - dependency-name: "org.eclipse.persistence:org.eclipse.persistence.jpa"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
