runtime: java
api_version: '1.0'
env: flexible
services:
  service: default
  handlers:
      - url: /.*
        proxy: backend
threadsafe: true
runtime_config:
  runtime_version: "17"
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 10

handlers:
  backend:
    url: https://${SERVICE_NAME}.appspot.com:8443/.*
automatic_scaling:
  #cool_down_period: 120s
  min_num_instances: 1
  max_num_instances: 2
liveness_check:
  initial_delay_sec: '300'
  check_interval_sec: '30'
  timeout_sec: '4'
  failure_threshold: 4
  success_threshold: 2
readiness_check:
  check_interval_sec: '5'
  timeout_sec: '4'
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: '300'
service_account: fineract-app-be@fineract-404214.iam.gserviceaccount.com
#entrypoint: java -Dloader.path=. -jar fineract-provider-0.0.1-SNAPSHOT.jar
#entrypoint: ["java", "-Dloader.path=.", "-jar", "/app/fineract-provider-0.0.1-SNAPSHOT.jar", "--port=8080"]
