steps:
  # Build the Java project and create a JAR file.
  - name: 'gcr.io/cloud-builders/gradle'
    args: [ 'build' ]

  # Build a Docker image for the Spring Boot application.
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/fineract', '.' ]

  # Push the Docker image to the Google Cloud Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${PROJECT_ID}/fineract' ]