steps:
  # Build the Java project and create a JAR file.
#  - name: 'gcr.io/cloud-builders/gradle'
#    args: [ 'clean', 'bootJar' ]

  # Build a Docker image for the Spring Boot application.
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west2-docker.pkg.dev/${PROJECT_ID}/fineract/fineract:latest', '.' ]

  # Push the Docker image to the Google Cloud Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west2-docker.pkg.dev/${PROJECT_ID}/fineract/fineract:latest' ]