site:
  title: Fineract Docs
  url: https://fineract.apache.org
  start_page: modules::index.adoc
antora:
  extensions:
  - require: '@antora/lunr-extension'
content:
  sources:
  - url: https://github.com/apache/fineract.git
    start_path: fineract-doc
ui:
  bundle:
    url: ui-bundle.zip
    snapshot: true
  
