name: Fineract Gradle build - basicauth
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
        mariad:
            image: mariadb:10.6
            ports:
                - 3306:3306
            env:
                MARIADB_ROOT_PASSWORD: mysql
            options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    env:
        TZ: Asia/Kolkata
    steps:
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Verify MariaDB connection
        run: |
            while ! mysqladmin ping -h"127.0.0.1" -P3306 ; do
                sleep 1
            done
      - name: Initialise databases
        run: |
            ./gradlew --no-daemon -q createDB -PdbName=fineract_tenants
            ./gradlew --no-daemon -q createDB -PdbName=fineract_default
      - name: Install additional software
        run: |
            sudo apt-get update
            sudo apt-get install ghostscript -y
      - name: Build & Test
        run: ./gradlew --no-daemon -q --console=plain licenseMain licenseTest check build test --fail-fast doc -x :twofactor-tests:test
