# This is the GitHub Action which
# automatically updates https://www.fineract.dev
#
# see https://jira.apache.org/jira/browse/FINERACT-970
# https://github.com/marketplace/actions/setup-gcloud-environment
# and http://blog2.vorburger.ch/2020/05/fineractdev-cicd-from-github-to-google.html
#
# Created by Michael Vorburger.ch for Fineract in May 2020.
#

name: Deploy to https://www.fineract.dev

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  setup-build-deploy:
    name: Deploy on Fineract.dev
    if: github.repository == 'apache/fineract'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - id: 'auth'
        uses: google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955 # tag=v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}'

      - uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb # tag=v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - run: gcloud components install beta

      - run: JOBS=$(gcloud beta builds list --ongoing --format="value[terminator=' '](id)") && [ ! -z "$JOBS" ] && echo "Cancelling $JOBS..." && gcloud builds cancel $JOBS --no-user-output-enabled || true

      - run: gcloud beta builds triggers list

      - run: gcloud beta builds triggers run deploy-demo --branch=master
