name: Sync Upstream Fineract

# This runs every hour
on:
  schedule:
    - cron: '0 * * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Sync
        run:  |
          set -ex;
          git config --local user.email "vidakovic@users.noreply.github.com";
          git config --local user.name  "Aleksandar Vidakovic";
          git remote add upstream "https://github.com/apache/fineract.git";
          git fetch upstream;
          git rebase upstream/develop develop;
          git push -f;
